-- Menu items table seeds here (Example)
-- INSERT INTO menu_items (name, description, menu_section, price) VALUES ('Big Mac', 'Nothing compares to two 100% Canadian beef patties, special sauce, crisp lettuce, processed cheddar cheese, pickles and onions on a toasted sesame seed bun.', 'Burgers', 2000);
