INSERT INTO menu_items (name, description, price, menu_section) VALUES ('vegan endive nachos', 'old fashioned, buttery and organic', 1900, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('Ultimate zucchini cakes', 'bold, flaky and organic', 1000, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('pan-fried chicken salad roll', 'old fashioned, buttery and gluten-free', 2100, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('mouth-watering rutabaga risotto', 'spicy and cruelty-free', 1000, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('mouth-watering cilantro nachos', 'zippy, glazed and fresh', 1400, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('mouth-watering broccoli nachos', 'crumbly and cruelty-free', 1300, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('fiesta endive risotto', 'zippy, crumbly and organic', 1300, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('broccoli wings', 'salty and fresh', 1700, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('fried lobster flatbread', 'tangy, tangy and local', 1900, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('zucchini cakes', 'salty and fresh', 900, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('ranch potato bites', 'zippy, flaky and local', 1800, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('dangerously cheesy basil bites', 'tangy, delicate and cruelty-free', 1300, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('rutabaga bites', 'crumbly and cruelty-free', 2300, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('au gratin chicken bun', 'zippy, sour and gluten-free', 2000, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('broccoli cakes', 'zesty, fermented and organic', 1900, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('fresh cherry tomato poutine', 'zippy, buttery and local', 1400, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('Ultimate lime flatbread', 'spicy and organic', 600, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('dangerously cheesy smoked bites', 'old fashioned, buttery and gluten-free', 1500, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('asparagus cakes', 'spicy and vegan', 800, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('endive cakes', 'tangy, flaky and local', 900, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('Southwest kale bun', 'beefy, flaky and local', 1600, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('local turnip flatbread', 'zippy, salty and cruelty-free', 1300, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('au gratin salmon salad roll', 'mouthsome, sweet and vegan', 1000, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('local salmon salad roll', 'beefy, flaky and cruelty-free', 1300, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('onion nachos', 'salty and cruelty-free', 1900, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('kids turnip roll', 'bold, buttery and organic', 800, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('gluten-free broccoli roll', 'tangy, spicy and house-made', 1400, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('mouth-watering potato salad roll', 'zippy, delicate and house-made', 1400, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('Ultimate cherry tomato bites', 'tangy, fermented and local', 1300, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('asparagus cakes', 'mouthsome, sour and seasonal', 700, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('jalapeño roasted cakes', 'zippy, tangy and seasonal', 1400, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('Ultimate garlic nachos', 'finger-lickin, pickled and house-made', 2000, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('Doritos steak gumbo', 'served over delicate thyme broth', 2000, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('farm-fresh oven-baked burger', 'with our signature delicate garlic-saffron sauce', 1500, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('beefy kids salad', 'drizzled with flaky garlic sauce', 2300, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('Ultimate chicken mac and cheese', 'with our signature finger-lickin curry mashed potatoes', 2300, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('gluten-free garlic-basil mac and cheese', 'smothered in a glazed cilantro-lemon mashed potatoes', 1900, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('house-made basil-saffron cheesesteak', 'stuffed with fermented cilantro-cilantro rice pilaf', 2200, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('organic lemon-chive gumbo', 'With seasonal fried turnip', 1700, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('mouthsome Tex-Mex salad', 'served with beefy double crunch polenta', 1000, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('cruelty-free saffron-saffron mac and cheese', 'With gluten-free broiled carrot', 2900, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('vegan roasted gumbo', 'With seasonal grilled avocado', 1100, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('bold kids burger', 'stuffed with spicy cilantro risotto', 1800, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('local lemon-rosemary burger', 'With seasonal smoked avocado', 2700, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('house-made basil-thyme mac and cheese', 'smothered in a finger-lickin ranch broth', 1600, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('fresh lemon-saffron sandwich', 'stuffed with tangy Kobe risotto', 1600, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('seasonal saffron-rosemary cheesesteak', 'smothered in a beefy Tex-Mex mashed potatoes', 1400, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('seasonal lime-rosemary burger', 'served with tangy garlic polenta', 2100, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('zesty ranch pizza', 'with our signature creamy saffron rice pilaf', 1500, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('Southwest tuna tataki cheesesteak', 'stuffed with buttery garlic broth', 1500, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('mouth-watering salmon salad', 'stuffed with finger-lickin Ultimate potatoes', 2400, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('Ultimate salmon mac and cheese', 'with our signature delicate saffron rice pilaf', 1900, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('house-made fried pasta', 'served with flaky garlic noodles', 2300, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('Bourbon Street lamb sandwich', 'stuffed with glazed lemon-chive rice pilaf', 2800, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('farm-fresh lime-saffron gumbo', 'packed with old fashioned cowboy rice pilaf', 2400, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('mouthsome Bourbon Street cheesesteak', 'served with sweet saffron rice pilaf', 1800, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('finger-lickin dangerously cheesy sandwich', 'drizzled with zesty Southwest rice pilaf', 1800, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('Doritos barbacoa cheesesteak', 'with our signature zippy jalapeño rice pilaf', 1800, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('fresh saffron-cilantro sandwich', 'smothered in a buttery lime-cilantro noodles', 2300, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('fresh chive-thyme gumbo', 'with our signature pickled rosemary polenta', 2200, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('local sautéed salad', 'packed with zippy double crunch noodles', 1900, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('Southwest prime rib pasta', 'With farm-fresh barbecued asparagus', 1500, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('cruelty-free rosemary-basil pasta', 'smothered in a zippy ranch potatoes', 2700, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('old fashioned Doritos mac and cheese', 'With house-made oven-baked kale', 2300, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('sizzling duck burger', 'served with crumbly chive mashed potatoes', 2000, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('zippy sizzling mac and cheese', 'With farm-fresh pan-fried turnip', 1900, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('organic broiled burger', 'With house-made broiled kale', 2200, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('mouthsome Doritos pizza', 'drizzled with beefy fiesta risotto', 2400, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('local sautéed gumbo', 'drizzled with tangy curry polenta', 1400, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('organic basil-saffron cheesesteak', 'With farm-fresh pan-fried zucchini', 1700, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('tangy dangerously cheesy gumbo', 'stuffed with delicate basil polenta', 2000, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('farm-fresh chive-garlic cheesesteak', 'served with salty garlic-saffron mashed potatoes', 1800, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('seasonal lemon-thyme gumbo', 'packed with glazed lemon potatoes', 1800, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('Tex-Mex lobster sandwich', 'packed with sweet lime sauce', 2100, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('house-made slow-roasted gumbo', 'packed with bold Doritos sauce', 2100, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('fresh pan-fried sandwich', 'With cruelty-free fried asparagus', 2100, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('finger-lickin mouth-watering sandwich', 'With house-made oven-baked broccoli', 1700, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('beefy Tex-Mex salad', 'with our signature sour saffron-basil noodles', 1400, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('fresh dry-roasted pasta', 'With house-made dry-roasted zucchini', 2300, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('Southwest carnitas cheesesteak', 'With local broiled carrot', 1700, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('mouthsome Southwest gumbo', 'served over creamy garlic-lime polenta', 1200, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('kids duck gumbo', 'drizzled with sour basil mashed potatoes', 2900, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('organic lime-cilantro mac and cheese', 'packed with tangy cowboy potatoes', 1500, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('vegan dry-roasted pasta', 'With house-made beer-battered onion', 2900, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('gluten-free rosemary-thyme gumbo', 'packed with tangy Southwest broth', 1800, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('zippy sizzling cheesesteak', 'With house-made sautéed asparagus', 1700, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('kids tofu pasta', 'smothered in a glazed chive noodles', 2900, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('fresh dry-roasted burger', 'with our signature sweet cilantro-lemon rice pilaf', 1800, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('tangy kids burger', 'served with flaky thyme-thyme broth', 2000, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('house-made lemon-garlic gumbo', 'packed with beefy Doritos sauce', 2100, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('gluten-free oven-baked salad', 'smothered in a zippy Tex-Mex polenta', 2000, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('bold Ultimate sandwich', 'With cruelty-free beer-battered leek', 1200, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('seasonal chive-thyme pizza', 'With local deep-fried kale', 2200, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('seasonal barbecued mac and cheese', 'smothered in a tangy Ultimate potatoes', 2300, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('fresh rosemary-cilantro mac and cheese', 'served over fermented rosemary polenta', 1400, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('double crunch carnitas gumbo', 'with our signature finger-lickin kids polenta', 2400, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('organic vanilla IPA', ' - ', 2100, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('bourbon lager', ' - ', 1800, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('lime lager', ' - ', 1600, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('bourbon martini', ' - ', 2000, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('farm-fresh bourbon lager', ' - ', 2000, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('salted caramel martini', ' - ', 2000, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('peach martini', ' - ', 1400, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('farm-fresh salted caramel paloma', ' - ', 1800, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('lemon vodka soda', ' - ', 2000, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('raspberry smoothie', ' - ', 2200, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('bourbon spritz', ' - ', 1100, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('apple vodka soda', ' - ', 1900, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('blueberry latte', ' - ', 1700, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('bourbon smoothie', ' - ', 1600, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('whisky paloma', ' - ', 1400, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('cilantro IPA', ' - ', 1700, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('whisky martini', ' - ', 1800, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('peach vodka soda', ' - ', 1400, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('bourbon vodka soda', ' - ', 700, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('house-made vanilla spritz', ' - ', 1100, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('local raspberry spritz', ' - ', 1100, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('rosemary martini', ' - ', 2300, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('cruelty-free pecan smoothie', ' - ', 1200, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('lemon paloma', ' - ', 1400, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('cilantro vodka soda', ' - ', 1600, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('vanilla vodka soda', ' - ', 1500, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('seasonal vodka soda', ' - ', 1500, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('local raspberry lager', ' - ', 1800, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('saffron latte', ' - ', 1700, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('fresh vodka soda', ' - ', 2300, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('peach vodka soda', ' - ', 2000, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('fresh vanilla spritz', ' - ', 2100, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('dry-roasted peach cheesecake', ' - ', 1200, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('au gratin pecan soufflé', ' - ', 2100, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('sautéed pecan ice cream', ' - ', 900, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('peach soufflé', ' - ', 900, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('house-made whisky pie', ' - ', 1100, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('apple donuts', ' - ', 1500, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('vegan raspberry pie', ' - ', 1200, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('deep-fried bourbon pie', ' - ', 900, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('fresh vanilla ice cream', ' - ', 1400, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('pecan cheesecake', ' - ', 2000, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('grilled pecan pie', ' - ', 2300, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('au gratin pecan soufflé', ' - ', 1900, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('pecan lava cake', ' - ', 2000, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('cruelty-free peach pie', ' - ', 1800, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('fresh pecan lava cake', ' - ', 2300, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('peach donuts', ' - ', 2300, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('blueberry sorbet', ' - ', 1600, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('seasonal peach donuts', ' - ', 1200, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('salted caramel soufflé', ' - ', 1500, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('vanilla sorbet', ' - ', 900, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('peach milkshake', ' - ', 2100, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('slow-roasted blueberry ice cream', ' - ', 2200, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('roasted salted caramel ice cream', ' - ', 700, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('slow-roasted salted caramel lava cake', ' - ', 800, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('peach sorbet', ' - ', 1400, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('bourbon lava cake', ' - ', 1000, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('slow-roasted raspberry soufflé', ' - ', 2000, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('au gratin apple cheesecake', ' - ', 1800, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('au gratin peach donuts', ' - ', 1200, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('cruelty-free pecan ice cream', ' - ', 900, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('roasted peach sorbet', ' - ', 1400, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('grilled salted caramel milkshake', ' - ', 900, 'Desserts'); 
