INSERT INTO menu_items (name, description, price, menu_section) VALUES ('rutabaga poutine', 'tangy and organic', 1800, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('oven-baked tuna tataki bun', 'tangy and cruelty-free', 900, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('smothered asparagus nachos', 'zippy, sour and gluten-free', 1400, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('dry-roasted tofu wings', 'bold, fermented and cruelty-free', 1600, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('seasonal montreal smoked meat poutine', 'glazed and organic', 1500, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('pan-fried chicken salad roll', 'sweet and fresh', 1300, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('leek risotto', 'bold, sweet and fresh', 1200, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('jalapeño cilantro salad roll', 'beefy, delicate and house-made', 1900, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('fiesta barbecued salad roll', 'finger-lickin, crumbly and house-made', 1500, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('oven-baked lamb bun', 'creamy and seasonal', 2000, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('fiesta saffron flatbread', 'zippy, sour and fresh', 900, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('Tex-Mex slow-roasted poutine', 'delicate and vegan', 1300, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('pan-fried barbacoa bites', 'glazed and local', 1400, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('seasonal tuna tataki wings', 'mouthsome, glazed and house-made', 1600, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('Southwest roasted roll', 'old fashioned, flaky and cruelty-free', 2100, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('curry zucchini flatbread', 'bold, flaky and cruelty-free', 1500, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('cruelty-free salmon cakes', 'finger-lickin, fermented and fresh', 1200, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('zucchini roll', 'mouthsome, fermented and cruelty-free', 1700, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('seasonal egg cakes', 'flaky and seasonal', 1900, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('kids rutabaga wings', 'bold, delicate and vegan', 800, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('sizzling lemon flatbread', 'sweet and organic', 1000, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('organic endive salad roll', 'beefy, sour and vegan', 900, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('Doritos slow-roasted roll', 'creamy and cruelty-free', 1100, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('au gratin duck salad roll', 'crumbly and organic', 1600, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('avocado poutine', 'buttery and fresh', 2000, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('mouth-watering fried bites', 'tangy, flaky and vegan', 1400, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('Kobe broccoli salad roll', 'crumbly and seasonal', 1700, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('local endive risotto', 'old fashioned, glazed and organic', 1900, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('Southwest broccoli flatbread', 'creamy and house-made', 1500, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('organic steak cakes', 'tangy, crumbly and house-made', 1600, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('cowboy deep-fried roll', 'tangy, buttery and local', 1200, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('vegan zucchini flatbread', 'fermented and organic', 1300, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('tangy Southwest gumbo', 'smothered in a sweet thyme-lemon polenta', 2800, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('mouthsome sizzling cheesesteak', 'served with bold Kobe sauce', 2000, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('beefy Doritos cheesesteak', 'stuffed with pickled lemon-chive sauce', 2900, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('ranch steak cheesesteak', 'packed with sour chive sauce', 1400, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('tangy sizzling gumbo', 'packed with salty rosemary-lemon polenta', 2100, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('mouth-watering lamb salad', 'served over bold kids sauce', 2600, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('vegan cilantro-rosemary gumbo', 'served over old fashioned dangerously cheesy sauce', 2100, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('farm-fresh fried gumbo', 'served with salty cilantro-cilantro potatoes', 2400, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('tangy double crunch salad', 'With vegan grilled cherry tomato', 1600, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('cowboy chicken salad', 'with our signature sweet lime-rosemary polenta', 1500, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('mouthsome ranch gumbo', 'smothered in a sour chive sauce', 2100, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('farm-fresh au gratin salad', 'With farm-fresh pan-fried rutabaga', 2200, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('Tex-Mex chicken salad', 'drizzled with salty thyme-basil mashed potatoes', 2600, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('seasonal lemon-cilantro burger', 'served over buttery rosemary-garlic noodles', 2100, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('tangy kids pasta', 'stuffed with fermented chive risotto', 1800, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('double crunch beef tataki mac and cheese', 'served with mouthsome curry broth', 1500, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('organic pan-fried pasta', 'smothered in a salty thyme risotto', 1300, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('fiesta tempeh sandwich', 'With seasonal barbecued avocado', 1600, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('bold sizzling mac and cheese', 'With cruelty-free pan-fried onion', 2000, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('zesty fiesta gumbo', 'served over spicy lemon-basil sauce', 1700, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('smothered tuna tataki cheesesteak', 'smothered in a spicy lemon sauce', 1700, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('organic smoked mac and cheese', 'with our signature sweet rosemary broth', 1400, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('Kobe prime rib gumbo', 'stuffed with tangy Tex-Mex risotto', 2100, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('local garlic-garlic salad', 'drizzled with crumbly garlic rice pilaf', 2500, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('organic slow-roasted pizza', 'drizzled with zesty dangerously cheesy risotto', 2300, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('local dry-roasted sandwich', 'smothered in a salty garlic broth', 1800, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('local oven-baked gumbo', 'packed with sour rosemary sauce', 1700, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('fresh lime-thyme salad', 'With organic fried potato', 1700, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('Tex-Mex carnitas gumbo', 'With seasonal smoked potato', 2800, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('Southwest montreal smoked meat salad', 'served over tangy smothered potatoes', 1800, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('Doritos beef tataki pizza', 'served over flaky chive rice pilaf', 2000, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('vegan barbecued burger', 'served over old fashioned double crunch broth', 2700, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('seasonal fried salad', 'With fresh oven-baked carrot', 1600, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('fresh basil-basil cheesesteak', 'stuffed with bold jalapeño noodles', 1400, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('cruelty-free pan-fried mac and cheese', 'With vegan oven-baked asparagus', 2900, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('beefy Ultimate salad', 'packed with bold Ultimate risotto', 2400, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('ranch shrimp mac and cheese', 'drizzled with flaky chive broth', 2100, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('bold Southwest salad', 'packed with delicate rosemary-cilantro broth', 1100, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('mouth-watering beef tataki sandwich', 'drizzled with salty lemon-garlic potatoes', 2200, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('organic slow-roasted cheesesteak', 'With farm-fresh deep-fried avocado', 1600, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('cowboy monkfish gumbo', 'With fresh fried carrot', 1200, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('gluten-free broiled sandwich', 'served with zippy Bourbon Street potatoes', 1600, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('tangy curry burger', 'With farm-fresh grilled broccoli', 2500, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('curry egg salad', 'served over fermented lemon-lime potatoes', 1500, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('house-made garlic-basil burger', 'smothered in a sour saffron-cilantro polenta', 1600, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('fresh au gratin cheesesteak', 'smothered in a old fashioned cowboy risotto', 1700, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('Southwest chicken mac and cheese', 'drizzled with spicy saffron-basil mashed potatoes', 2500, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('mouth-watering tempeh sandwich', 'packed with delicate saffron-saffron rice pilaf', 2300, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('Bourbon Street steak sandwich', 'drizzled with creamy saffron polenta', 1900, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('tangy curry mac and cheese', 'stuffed with beefy jalapeño potatoes', 1100, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('smothered steak gumbo', 'drizzled with creamy lemon-lemon sauce', 2700, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('farm-fresh chive-chive sandwich', 'With house-made deep-fried broccoli', 1500, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('house-made dry-roasted sandwich', 'smothered in a finger-lickin Kobe polenta', 2200, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('Doritos steak salad', 'stuffed with zippy smothered sauce', 1600, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('farm-fresh pan-fried pasta', 'served over sweet basil potatoes', 2100, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('ranch chicken salad', 'served over bold mouth-watering risotto', 1600, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('seasonal chive-thyme pasta', 'served over delicate rosemary sauce', 1800, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('cruelty-free barbecued salad', 'served over flaky chive-saffron broth', 2100, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('farm-fresh cilantro-garlic mac and cheese', 'with our signature flaky lemon risotto', 1800, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('Tex-Mex tuna tataki sandwich', 'served with delicate lemon-chive broth', 1500, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('Bourbon Street tofu gumbo', 'served with sour thyme polenta', 2300, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('dangerously cheesy beef tataki mac and cheese', 'With fresh roasted endive', 1800, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('old fashioned fiesta salad', 'served over crumbly cilantro-thyme risotto', 2600, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('Southwest montreal smoked meat pizza', 'served over mouthsome smothered rice pilaf', 2000, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('organic lager', ' - ', 1600, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('blueberry lager', ' - ', 2300, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('apple martini', ' - ', 2300, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('seasonal raspberry lager', ' - ', 1800, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('bourbon spritz', ' - ', 2000, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('chive latte', ' - ', 1100, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('pecan vodka soda', ' - ', 1500, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('fresh paloma', ' - ', 2200, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('gluten-free salted caramel lager', ' - ', 2200, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('gluten-free spritz', ' - ', 700, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('local peach spritz', ' - ', 2100, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('organic bourbon spritz', ' - ', 2400, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('gluten-free peach spritz', ' - ', 1700, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('vegan raspberry lager', ' - ', 800, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('farm-fresh IPA', ' - ', 1600, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('blueberry IPA', ' - ', 1300, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('bourbon latte', ' - ', 1600, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('lime paloma', ' - ', 2000, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('salted caramel IPA', ' - ', 1300, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('house-made apple spritz', ' - ', 1300, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('house-made blueberry smoothie', ' - ', 1100, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('organic smoothie', ' - ', 1800, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('vanilla spritz', ' - ', 1100, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('house-made latte', ' - ', 2100, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('fresh salted caramel spritz', ' - ', 1900, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('bourbon latte', ' - ', 800, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('whisky lager', ' - ', 2100, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('vegan martini', ' - ', 1800, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('farm-fresh martini', ' - ', 1000, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('lemon daiquiri', ' - ', 900, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('vegan raspberry IPA', ' - ', 2000, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('cilantro martini', ' - ', 1100, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('bourbon lava cake', ' - ', 1700, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('broiled whisky lava cake', ' - ', 1600, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('bourbon soufflé', ' - ', 2200, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('pan-fried vanilla pie', ' - ', 2200, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('local pecan milkshake', ' - ', 2100, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('peach pie', ' - ', 1800, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('seasonal raspberry pie', ' - ', 1600, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('whisky cheesecake', ' - ', 1200, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('fresh blueberry sorbet', ' - ', 1200, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('gluten-free raspberry milkshake', ' - ', 2100, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('cruelty-free raspberry cheesecake', ' - ', 1200, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('oven-baked whisky milkshake', ' - ', 1600, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('grilled blueberry pie', ' - ', 800, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('oven-baked raspberry milkshake', ' - ', 2000, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('raspberry cheesecake', ' - ', 2100, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('salted caramel sorbet', ' - ', 1800, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('fried vanilla soufflé', ' - ', 1300, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('apple milkshake', ' - ', 2000, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('raspberry ice cream', ' - ', 1000, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('slow-roasted apple milkshake', ' - ', 1500, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('smoked blueberry lava cake', ' - ', 1300, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('local vanilla cheesecake', ' - ', 2300, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('grilled bourbon pie', ' - ', 2000, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('pan-fried vanilla donuts', ' - ', 2200, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('farm-fresh blueberry milkshake', ' - ', 1900, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('grilled bourbon ice cream', ' - ', 900, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('broiled blueberry sorbet', ' - ', 2300, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('seasonal apple ice cream', ' - ', 2200, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('cruelty-free salted caramel milkshake', ' - ', 1500, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('smoked salted caramel donuts', ' - ', 1000, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('local peach lava cake', ' - ', 2400, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('oven-baked raspberry lava cake', ' - ', 1900, 'Desserts'); 
