INSERT INTO menu_items (name, description, price, menu_section) VALUES ('curry onion wings', 'zippy, delicate and fresh', 1100, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('gluten-free broccoli bun', 'bold, spicy and organic', 1300, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('double crunch cherry tomato wings', 'creamy and local', 1400, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('Kobe saffron bun', 'beefy, crumbly and organic', 2000, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('carrot bun', 'mouthsome, spicy and vegan', 2200, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('seasonal zucchini salad roll', 'delicate and fresh', 1300, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('sizzling rosemary bun', 'spicy and seasonal', 1400, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('organic tempeh bun', 'zesty, salty and cruelty-free', 1600, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('endive flatbread', 'tangy, flaky and seasonal', 1000, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('carrot salad roll', 'mouthsome, flaky and house-made', 1500, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('seasonal steak roll', 'crumbly and cruelty-free', 2100, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('fresh lobster flatbread', 'tangy and house-made', 1900, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('au gratin prime rib flatbread', 'glazed and farm-fresh', 1800, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('leek risotto', 'zippy, sweet and cruelty-free', 2000, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('dangerously cheesy cherry tomato cakes', 'creamy and organic', 1100, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('Bourbon Street kale wings', 'sweet and farm-fresh', 1700, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('dangerously cheesy thyme salad roll', 'zippy, crumbly and gluten-free', 2100, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('Ultimate garlic flatbread', 'tangy, fermented and cruelty-free', 700, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('Bourbon Street chive salad roll', 'tangy, sweet and vegan', 2200, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('fresh salmon roll', 'glazed and vegan', 1500, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('cruelty-free carrot flatbread', 'mouthsome, tangy and seasonal', 1600, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('Tex-Mex slow-roasted flatbread', 'old fashioned, delicate and house-made', 1500, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('broiled carnitas poutine', 'finger-lickin, sweet and gluten-free', 700, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('house-made onion flatbread', 'flaky and vegan', 800, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('avocado nachos', 'finger-lickin, buttery and farm-fresh', 1800, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('asparagus nachos', 'tangy and organic', 2300, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('rutabaga poutine', 'old fashioned, buttery and fresh', 1700, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('dry-roasted lamb roll', 'fermented and farm-fresh', 1100, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('Bourbon Street cilantro poutine', 'mouthsome, salty and house-made', 1900, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('kale roll', 'glazed and farm-fresh', 1900, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('cruelty-free potato poutine', 'creamy and organic', 900, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('fresh beef tataki bun', 'fermented and seasonal', 1500, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('vegan zucchini roll', 'tangy, crumbly and vegan', 1400, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('dangerously cheesy chive roll', 'delicate and house-made', 2100, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('curry turnip nachos', 'mouthsome, flaky and farm-fresh', 1100, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('Southwest beer-battered bites', 'delicate and fresh', 1000, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('asparagus salad roll', 'pickled and house-made', 1400, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('smothered kale flatbread', 'finger-lickin, flaky and fresh', 1400, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('Kobe dry-roasted bun', 'salty and local', 1400, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('house-made endive salad roll', 'zippy, spicy and local', 1000, 'Appetizers'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('cruelty-free basil-garlic burger', 'stuffed with bold Kobe rice pilaf', 2500, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('zippy Doritos pasta', 'smothered in a zesty Southwest rice pilaf', 2400, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('seasonal garlic-garlic pasta', 'served over zippy sizzling risotto', 2700, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('bold curry cheesesteak', 'With cruelty-free roasted leek', 2300, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('double crunch beef tataki cheesesteak', 'stuffed with tangy lime broth', 2400, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('house-made garlic-garlic sandwich', 'stuffed with glazed lemon-garlic potatoes', 3000, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('bold Kobe burger', 'smothered in a sour rosemary-lemon rice pilaf', 2500, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('fresh smoked burger', 'drizzled with spicy lime-rosemary potatoes', 2200, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('curry prime rib mac and cheese', 'with our signature mouthsome Tex-Mex rice pilaf', 1600, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('zesty Kobe gumbo', 'drizzled with tangy sizzling risotto', 1800, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('farm-fresh garlic-chive burger', 'drizzled with zippy curry polenta', 1500, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('house-made chive-basil salad', 'stuffed with crumbly lime-saffron risotto', 1700, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('sizzling carnitas burger', 'packed with pickled garlic-cilantro rice pilaf', 1700, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('smothered lobster burger', 'served over spicy basil-lime polenta', 1400, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('old fashioned Doritos pasta', 'drizzled with old fashioned cowboy mashed potatoes', 2200, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('mouthsome Doritos burger', 'served with old fashioned smothered potatoes', 2800, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('vegan rosemary-basil mac and cheese', 'With vegan sautéed onion', 2000, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('mouthsome smothered pasta', 'served over old fashioned Kobe mashed potatoes', 1900, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('organic au gratin sandwich', 'With gluten-free au gratin asparagus', 1600, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('cruelty-free smoked pizza', 'served with zippy double crunch sauce', 1500, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('fresh cilantro-basil salad', 'smothered in a glazed thyme-rosemary risotto', 2000, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('house-made deep-fried pasta', 'drizzled with glazed saffron broth', 1400, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('local saffron-lime gumbo', 'With organic deep-fried onion', 2600, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('vegan au gratin burger', 'served with fermented basil-rosemary broth', 2300, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('fiesta prime rib salad', 'served over sweet chive risotto', 2400, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('bold kids salad', 'drizzled with glazed basil-basil rice pilaf', 1200, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('zesty Southwest mac and cheese', 'with our signature beefy Kobe sauce', 2600, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('house-made barbecued cheesesteak', 'With farm-fresh oven-baked avocado', 2600, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('gluten-free thyme-lime salad', 'packed with tangy Tex-Mex broth', 2600, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('bold Tex-Mex gumbo', 'drizzled with delicate chive noodles', 1100, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('farm-fresh thyme-rosemary gumbo', 'served over beefy double crunch polenta', 2300, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('old fashioned mouth-watering pasta', 'served with sour chive sauce', 1900, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('gluten-free basil-thyme gumbo', 'served with zesty mouth-watering sauce', 2300, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('zippy jalapeño mac and cheese', 'with our signature mouthsome sizzling potatoes', 1700, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('old fashioned dangerously cheesy pizza', 'served over crumbly lemon risotto', 1600, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('old fashioned Bourbon Street cheesesteak', 'smothered in a bold ranch noodles', 1600, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('farm-fresh lemon-rosemary pizza', 'With vegan barbecued asparagus', 1300, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('bold jalapeño cheesesteak', 'served with tangy jalapeño mashed potatoes', 1700, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('fiesta shrimp cheesesteak', 'packed with crumbly lemon-chive noodles', 1300, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('bold Kobe pasta', 'With local roasted asparagus', 2000, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('tangy sizzling burger', 'served over buttery rosemary polenta', 2800, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('local broiled pasta', 'stuffed with crumbly chive potatoes', 2800, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('zippy Kobe salad', 'With seasonal fried carrot', 1700, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('Doritos beef tataki salad', 'with our signature tangy Bourbon Street polenta', 1300, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('farm-fresh roasted pasta', 'served with creamy saffron-lemon polenta', 1200, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('organic au gratin burger', 'With organic fried asparagus', 2200, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('jalapeño shrimp mac and cheese', 'With local oven-baked avocado', 1600, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('Southwest carnitas salad', 'drizzled with sour rosemary sauce', 1500, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('vegan thyme-garlic pizza', 'with our signature delicate rosemary-saffron polenta', 2400, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('cruelty-free lime-basil pizza', 'With fresh barbecued potato', 1700, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('tangy ranch burger', 'served over creamy lemon broth', 1700, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('Tex-Mex duck pizza', 'served with crumbly chive broth', 1100, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('farm-fresh slow-roasted sandwich', 'served over pickled saffron risotto', 2300, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('bold mouth-watering burger', 'drizzled with salty saffron-saffron mashed potatoes', 2600, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('gluten-free chive-saffron cheesesteak', 'packed with salty cilantro-basil risotto', 1900, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('Tex-Mex beef tataki sandwich', 'drizzled with creamy cilantro risotto', 2400, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('seasonal barbecued sandwich', 'served with bold Southwest rice pilaf', 2100, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('finger-lickin Doritos sandwich', 'drizzled with finger-lickin jalapeño polenta', 2600, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('old fashioned ranch cheesesteak', 'With fresh broiled asparagus', 1200, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('dangerously cheesy prime rib pasta', 'With farm-fresh broiled carrot', 2600, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('curry pork sandwich', 'With fresh oven-baked cherry tomato', 2000, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('house-made smoked sandwich', 'stuffed with creamy lemon-saffron polenta', 2000, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('gluten-free smoked cheesesteak', 'with our signature fermented chive potatoes', 1600, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('Doritos shrimp burger', 'stuffed with delicate saffron-lemon risotto', 1900, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('mouth-watering monkfish burger', 'With gluten-free smoked carrot', 1400, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('smothered monkfish mac and cheese', 'drizzled with creamy saffron risotto', 2500, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('fresh smoked pizza', 'drizzled with tangy saffron potatoes', 1200, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('sizzling lamb sandwich', 'served with creamy thyme rice pilaf', 2000, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('vegan lemon-chive gumbo', 'drizzled with sweet thyme risotto', 2200, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('house-made lime-cilantro salad', 'smothered in a flaky lime-rosemary potatoes', 2400, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('curry cod cheesesteak', 'With gluten-free deep-fried broccoli', 1200, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('Bourbon Street carnitas pizza', 'With seasonal broiled avocado', 1800, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('cruelty-free beer-battered cheesesteak', 'served with spicy lemon-lime sauce', 2300, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('Tex-Mex beef tataki pizza', 'smothered in a tangy saffron potatoes', 2100, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('bold Ultimate pizza', 'served with zesty cowboy rice pilaf', 2100, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('bold jalapeño gumbo', 'with our signature finger-lickin cowboy risotto', 2500, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('zippy Bourbon Street burger', 'drizzled with tangy lime-lime mashed potatoes', 2800, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('finger-lickin mouth-watering cheesesteak', 'packed with sour basil-lemon sauce', 2400, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('seasonal basil-basil burger', 'served with glazed lemon-chive risotto', 3000, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('gluten-free oven-baked cheesesteak', 'drizzled with sour basil-cilantro sauce', 2000, 'Entrees'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('apple spritz', ' - ', 1000, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('rosemary vodka soda', ' - ', 1900, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('chive IPA', ' - ', 2000, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('lemon vodka soda', ' - ', 1500, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('saffron IPA', ' - ', 700, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('bourbon latte', ' - ', 1600, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('vegan spritz', ' - ', 1300, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('cruelty-free daiquiri', ' - ', 1400, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('lime daiquiri', ' - ', 2400, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('local apple latte', ' - ', 1000, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('garlic smoothie', ' - ', 1900, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('house-made martini', ' - ', 800, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('organic paloma', ' - ', 1900, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('local vanilla martini', ' - ', 600, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('pecan vodka soda', ' - ', 1500, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('pecan lager', ' - ', 1000, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('vegan bourbon smoothie', ' - ', 900, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('farm-fresh blueberry latte', ' - ', 1500, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('fresh vodka soda', ' - ', 1300, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('vegan salted caramel martini', ' - ', 1000, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('rosemary paloma', ' - ', 2100, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('cruelty-free martini', ' - ', 1800, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('cruelty-free whisky lager', ' - ', 2200, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('vanilla IPA', ' - ', 1200, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('raspberry spritz', ' - ', 2000, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('whisky paloma', ' - ', 2000, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('cruelty-free vanilla latte', ' - ', 1100, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('vanilla smoothie', ' - ', 1200, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('fresh raspberry martini', ' - ', 800, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('cilantro smoothie', ' - ', 1100, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('gluten-free peach spritz', ' - ', 2200, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('house-made bourbon vodka soda', ' - ', 1000, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('whisky martini', ' - ', 1300, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('saffron paloma', ' - ', 2200, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('gluten-free blueberry martini', ' - ', 900, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('gluten-free martini', ' - ', 2200, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('organic smoothie', ' - ', 700, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('blueberry spritz', ' - ', 1200, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('vanilla daiquiri', ' - ', 1200, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('seasonal blueberry lager', ' - ', 1300, 'Drinks'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('sautéed peach donuts', ' - ', 2100, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('dry-roasted pecan ice cream', ' - ', 1500, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('deep-fried salted caramel lava cake', ' - ', 1700, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('smoked pecan milkshake', ' - ', 1800, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('vanilla soufflé', ' - ', 1500, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('farm-fresh raspberry pie', ' - ', 900, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('bourbon cheesecake', ' - ', 2300, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('roasted vanilla sorbet', ' - ', 1200, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('slow-roasted vanilla pie', ' - ', 900, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('pecan donuts', ' - ', 1900, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('oven-baked vanilla ice cream', ' - ', 2000, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('raspberry lava cake', ' - ', 2200, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('fresh blueberry lava cake', ' - ', 2400, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('dry-roasted pecan cheesecake', ' - ', 900, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('bourbon pie', ' - ', 1500, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('gluten-free apple milkshake', ' - ', 1900, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('salted caramel soufflé', ' - ', 1000, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('raspberry lava cake', ' - ', 1500, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('vegan peach milkshake', ' - ', 800, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('raspberry lava cake', ' - ', 1100, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('whisky soufflé', ' - ', 1000, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('smoked bourbon soufflé', ' - ', 2200, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('fried apple milkshake', ' - ', 1600, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('beer-battered blueberry soufflé', ' - ', 1900, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('roasted apple lava cake', ' - ', 1400, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('deep-fried apple lava cake', ' - ', 1100, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('vegan whisky lava cake', ' - ', 2100, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('local blueberry lava cake', ' - ', 700, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('apple sorbet', ' - ', 1600, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('cruelty-free vanilla milkshake', ' - ', 1600, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('slow-roasted salted caramel cheesecake', ' - ', 1000, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('deep-fried raspberry milkshake', ' - ', 1600, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('apple pie', ' - ', 2100, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('pecan ice cream', ' - ', 900, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('pecan donuts', ' - ', 1500, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('fresh raspberry pie', ' - ', 1500, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('salted caramel sorbet', ' - ', 2000, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('cruelty-free whisky milkshake', ' - ', 1400, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('raspberry pie', ' - ', 1000, 'Desserts'); 
INSERT INTO menu_items (name, description, price, menu_section) VALUES ('au gratin blueberry soufflé', ' - ', 2000, 'Desserts'); 
